#feature 55 - created native app: which is displaying the (input) fields dynamically. - after stopping the scan process, the result list gets clickable. - long press on a record will display more info to this tag. - after selecting records, the location, room and employee drop down menu will be shown. - TODO: filling room and employee drop down choices is not working yet! after choosing a location, a NoClassDefFoundError will be shown. there is something wrong with including our web project classes...