because the production server is running with JRE 6 and we were facing NoSuchMethodErrors because Integer.compare() is introduced in JRE 7: - changed the Integer.compare() function to a similar expression using compareTo() - changed the project setup to java version 1.6
- reverted the the parameter from the DatabaseHandlers 
getRecordFromDatabseById() methods back to int